version: '3'

services:

    nginx:
      image: nginx:alpine
      build:
        context: ./docker/nginx/
        dockerfile: ./Dockerfile
      container_name: bernard_nginx
      volumes:
        - .:/var/www/html:ro
#        - ./var/nginx:/var/log/nginx
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - 80:80
        - 443:443
      depends_on:
        - backend

    backend:
      image: php:latest
      container_name: bernard_backend
      build:
        context: .
        dockerfile: ./Dockerfile
      restart: always
      volumes:
        - .:/var/www/html
      expose:
        - 9000
      depends_on:
        - mysql

    mysql:
      image: mysql:8.0
      container_name: bernard_mysql
      command: --default-authentication-plugin=mysql_native_password
      environment:
        - MYSQL_ROOT_PASSWORD=asdf
        - MYSQL_DATABASE=bernard
      ports:
        - 33062:3306
      volumes:
        - ./var/mysql-data:/var/lib/mysql


    adminer:
      image: adminer:latest
      container_name: bernard_adminer
      restart: always
      ports:
        - 8080:8080

    rabbitmq:
      image: rabbitmq:3-management-alpine
      hostname: bernard-rabbitmq
      build:
        context: ./docker/rabbitmq/
        dockerfile: ./Dockerfile
      container_name: bernard_rabbitmq
      environment:
        - RABBITMQ_ERLANG_COOKIE=7ead507151fc4461b9f45c1161384a04
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
        - RABBITMQ_DEFAULT_VHOST=/
      ports:
        - 15672:15672
      volumes:
        - ./var/rabbitmq:/var/lib/rabbitmq
